modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/yadler97/unbelievable-minecraft-mod/issues"
[[mods]]
modId="unbelievablemod"
version="${file.jarVersion}"
displayName="Yannick's Unbelievable Mod"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/yadler97/unbelievable-minecraft-mod"
logoFile="unbelievablemod.png"
credits="Yannick Adler"
authors="Yannick Adler"
description='''
A truly unbelievable Mod adding new blocks, items, ores, structures and more!
'''

[[dependencies.unbelievablemod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unbelievablemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
